swagger: "2.0"
info:
  description: "누구든지 스터디를 만들고 자신이 원하는 스터디에 참여할 수 있다. "
  version: "1.0.0"
  title: "Franchise"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "joenggyu0@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "franchise"
basePath: "/v1"
schemes:
  - "http"
paths:
  /recruits:
    post:
      tags:
        - "recruits"
      summary: "새로운 모집을 생성합니다."
      operationId: "createRecruit"
      description: "새로운 모집을 생성합니다."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Recruit를 생성하기 위한 요소을 포함합니다."
          required: true
          schema:
            $ref: "#/definitions/RecruitCreateModel"
      responses:
        "200":
          description: "성공적으로 모집을 생성했음."
          schema:
            $ref: "#/definitions/RecruitModel"
        "400":
          description: "
          - 제목, 또는 마감일시를 입력하지 않았을 경우 <br>
          - 제목의 글자수가 2자 이하일 경우. <br>
          - 마감일시를 현재보다 과거를 했을 경우 <br>
          "
        "500":
          description: "생성자가 존재하지 않을 경우"

  /recruits/recruit/{recruitId}:
    put:
      tags:
        - "recruits"
      summary: "모집 정보를 변경합니다."
      operationId: "updateRecruitContents"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "recruitId"
          description: "특정 모집을 식별하기 위한 Property"
          required: true
          type: string
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/RecruitUpdateModel"
      responses:
        "200":
          description: "성공적으로 변경시 RecruitModel 반환"
          schema:
            $ref: "#/definitions/RecruitModel"
        "400":
          description: "제목, 마감일자가 존재하지 않을 경우 400 반환"
        "500":
          description: "생성자가 존재하지 않을 경우 500 반환"
    get:
      tags:
        - "recruits"
      summary: "특정 모집의 정보를 조회합니다."
      operationId: "getRecruitById"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "recruitId"
          description: "특정 모집을 식별하기 위한 Property"
          required: true
          type: string
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/RecruitUpdateModel"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RecruitModel"
        500:
          description: "생성자가 존재하지 않을 경우 500 반환"


  /recruits/{recruitId}/status:
    put:
      tags:
        - "recruits"
      summary: "특정 모집의 상태를 변경합니다."
      operationId: "recruitStatusChange"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "recruitId"
          description: "특정 모집을 식별하기 위한 Property"
          required: true
          type: string
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/RecruitUpdateModel"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/RecruitModel"
        500:
          description: "만든이, 제목, 마감일자가 존재하지 않는다면 500 반환"
definitions:
  RecruitModel:
    type: object
    additionalProperties: true
    properties:
      recruitId:
        description: 모집을 식별하기 위한 ID
        type: string
      creator:
        description: 모집을 만든 사람
        type: string
      title:
        description: 모집의 제목
        type: string
      contents:
        type: string
      deadlineDate:
        type: string
        format: date-time
      inquires:
        description: 모집의 질의문
        type: array
        items:
          $ref: "#/definitions/InquiryModel"
      status:
        type: string
        description: "모집의 상태를 나타내며, 모집을 처음 생성시 START,
        사람을 모일 수 있는 상태를 BEGIN, 모집의 종료를 나타내는 FINISH"
        enum:
          - "START"
          - "BEGIN"
          - "FINISH"
    xml:
      name: "Recruit"
  InquiryModel:
    type: object
    properties:
      creator:
        type: string
      question:
        type: string
      required:
        type: boolean
  RecruitCreateModel:
    type: object
    properties:
      creator:
        type: string
      title:
        type: string
      contents:
        type: string
      deadlineDate:
        type: string
        format: date-time
  RecruitUpdateModel:
    type: object
    properties:
      creator:
        type: string
      title:
        type: string
      contents:
        type: string
      deadlineDate:
        type: string
        format: date-time
    xml:
      name: "Recruit"