version: '2'
services:
  slipping-mysql:
    image: mysql:8.0.20
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=slipp
      - MYSQL_PASSWORD=slipppw
      - MYSQL_DATABASE=slipping
    ports:
      - 3377:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
